version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Pass environment variables from an .env file
      - NODE_ENV=development
      - PORT=8000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
