name: Node.js CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Clear npm cache and node_modules
    - name: Clean Install
      run: |
        npm cache clean --force
        rm -rf node_modules
        rm -rf package-lock.json
    
    # Install dependencies
    - name: Install Dependencies
      run: |
        npm install
        npm install dotenv
    
    # Create .env
    - name: Create .env file
      run: |
        echo "${{secrets.PROD_ENV_FILE}}" > .env
    
    # Start/Restart PM2
    - name: Start/Restart PM2
      run: |
        pm2 list
        if pm2 list | grep -q "BackendAPI"; then
          pm2 restart BackendAPI --update-env
        else
          pm2 start npm --name "BackendAPI" -- start
        fi
        pm2 save
